Ticket 12
OwenPortfolio/FE-nc-news pull request #9
Opened 2022-06-16 15:31 UTC by OwenPortfolio

Add error handling for non-existant paths, and topic or article Ids.

2022-06-16 15:42 UTC, emilyb93 reviewed
You have a bug where if you go to 'articles/topics/notatopic' , you get the error 404, but you cannot actually remove the error by clicking the topic links.

2022-06-16 15:42 UTC, emilyb93 reviewed
You also have a bug where going to something '/articles/fsfasf' it doesnt show an error, you get a react issue

2022-06-16 15:43 UTC, emilyb93 commented on src/components/SingleTopic.jsx
> +                setLoading(false);
You need to setError to false here as well or you can get caught in an error page

2022-06-16 15:45 UTC, emilyb93 commented on src/components/Article.jsx
> +    } else if(error === 404){
The error might not be a 404 if we make a bad request with requesting an id of a string, we get a 400 which is causing this error component to not work correctly. A better way would be to just say if(error)

2022-06-16 15:45 UTC, emilyb93 requested changes
Some error bugs

2022-06-16 15:55 UTC, OwenPortfolio commented
All fixed (I hope)

2022-06-17 10:06 UTC, dappernerddesigns commented
All bugs smooshed. Merge away :)

2022-06-17 10:07 UTC, OwenPortfolio commented
Glad to see you're not slacking on your last day. ;) Thanks

2022-06-17 10:07 UTC, merged